# Lab Instructions

Find a dataset that interests you. I'd recommend starting on [Kaggle](https://www.kaggle.com/). Read through all of the material about the dataset and download a .CSV file.

1. Write a short summary of the data.  Where did it come from?  How was it collected?  What are the features in the data?  Why is this dataset interesting to you?  

2. Identify 5 interesting questions about your data that you can answer using Pandas methods.  

3. Answer those questions!  You may use any method you want (including LLMs) to help you write your code; however, you should use Pandas to find the answers.  LLMs will not always write code in this way without specific instruction.  

4. Write the answer to your question in a text box underneath the code you used to calculate the answer.

1. Write a short summary of the data. Where did it come from? How was it collected? What are the features in the data? Why is this dataset interesting to you?

While searching through kaggle for datasets I found the "Formula 1 Grand Prix Winners Dataset (1950–2025)" and thought it was interesting I am interested in racing and cars in general so I tought this data set was good for the assignmnet, it was also simple and small enough to work with but big enough to have quite a bit of data so it was perfect. The data was most likely collected through official Fromula 1 records, and the features in the data include:

- date
- continent
- grand_prix
- circuit
- winner_name
- team
- time
- laps
- year

2. Identify 5 interesting questions about your data that you can answer using Pandas methods.

Questions:
1. What Grand Prix(s) did Max Verstappen win?
2. What was his best lap time through all the Grand Prix he's won?
3. what year did he win?
4. What is Max Verstappens best track?
5. What team was Max Verstappen in at the time?

3. Answer those questions! You may use any method you want (including LLMs) to help you write your code; however, you should use Pandas to find the answers. LLMs will not always write code in this way without specific instruction.
4. Write the answer to your question in a text box underneath the code you used to calculate the answer.

In [1]:
# Setup Data Set
import pandas as pd

df = pd.read_csv("winners_f1_1950_2025_v2.csv")

df.head()

,date,continent,grand_prix,circuit,winner_name,team,time,laps,year
0,1950-05-13,Europe,Great Britain,Silverstone Circuit,Nino Farina,Alfa Romeo,02:13:23,70.0,1950
1,1950-05-21,Europe,Monaco,Circuit de Monaco,Juan Manuel Fangio,Alfa Romeo,03:13:18,100.0,1950
2,1950-05-30,North America,United States,Indianapolis Motor Speedway,Johnnie Parsons,Kurtis Kraft Offenhauser,02:46:55,138.0,1950
3,1950-06-04,Europe,Switzerland,Circuit Bremgarten,Nino Farina,Alfa Romeo,02:02:53,42.0,1950
4,1950-06-18,Europe,Belgium,Circuit de Spa Francorchamps,Juan Manuel Fangio,Alfa Romeo,02:47:26,35.0,1950

In [20]:
# Answer 1: 
max_wins = df[df["winner_name"] == "Max Verstappen"]

max_wins[["grand_prix"]]

     grand_prix
942       Spain
973    Malaysia
976      Mexico
987     Austria
997      Mexico
...         ...
1113      Spain
1124     Brazil
1126      Qatar
1130      Japan
1134      Italy

[65 rows x 1 columns]

From the output we can analyze that Max verstappen has won 60+ Grand Prix, in many places such as Spain Malaysia, Mexico, and Austria. Not just one Grand Prix but many.

In [30]:
# Answer 2:
best_lap = max_wins["time"].min()

win = max_wins.loc[max_wins["time"] == best_lap]

win.head()

,date,continent,grand_prix,circuit,winner_name,team,time,laps,year
1095,2023-09-03,Europe,Italy,Autodromo Nazionale di Monza,Max Verstappen,Red Bull Racing Honda RBPT,01:13:41,51.0,2023

The output tells us that Max Verstappen's best lap was 1:13:41 and it was in the "Autodromo Nazionale di Monza" circuit in Italy

In [35]:
# Answer 3:
max_wins.groupby("year").size().sort_values(ascending=True)

year
2016     1
2017     2
2018     2
2019     3
2020     2
2021    10
2022    15
2023    19
2024     9
2025     2
dtype: int64

In [ ]:
He won races every year from 2016 to 2025 an has multiple wins every year besided 2016. The answer to this question is extremely suprising because I did not know this an just goes to show why he is widely considered one of the
greatest racers of all time.

In [45]:
# Answer 4:
max_wins.groupby("circuit").size().sort_values(ascending=True)

circuit
Albert Park Circuit                             1
Baku City Circuit                               1
Hockenheimring                                  1
Shanghai International Circuit                  1
Sepang International Circuit                    1
Hungaroring                                     2
Circuit de Monaco                               2
Bahrain International Circuit                   2
Lusail International Circuit                    2
Jeddah Corniche Circuit                         2
Miami International Autodrome                   2
Silverstone Circuit                             2
Circuit Paul Ricard                             2
Circuit Gilles Villeneuve                       3
Circuit de Spa Francorchamps                    3
Autodromo Internazionale Enzo e Dino Ferrari    3
Autodromo Nazionale di Monza                    3
Autodromo José Carlos Pace                      3
Circuit Zandvoort                               3
Circuit de Barcelona Catalunya                  4
Suzuka International Racing Course              4
Circuit of the Americas                         4
Yas Marina Circuit                              4
Autódromo Hermanos Rodríguez                    5
Red Bull Ring                                   5
dtype: int64

The data analysis tells us that "Autodromo Hermanos Rodriguez" and "Red Bull Ring" are his best tracks in which he has won 5 Grand Prix in both of those tracks.

In [47]:
# Answer 5:
max_wins.groupby("team").size().sort_values(ascending=True)

team
Red Bull Racing                2
Red Bull Racing TAG Heuer      5
Red Bull Racing RBPT          15
Red Bull Racing Honda         15
Red Bull Racing Honda RBPT    28
dtype: int64

Max Verstappen has won the most with Red "Bull Racing Honda RBPT" team, with 28 total Grand Prix wins!